# Partial configuration only!
# Because this is only a learning project, there is no deployment to a target system.
# Either start it locally with Testcontainers for Kafka (and other infrastructure components)
# using profile 'local' or run the tests which has its own application.yml

api:
  version: v1

spring:
  application:
    name: bookworm


  liquibase:
    enabled: true
    change-log: "classpath:db/changelog/db.changelog-master.yaml"
    show-summary: verbose
    show-summary-output: console

  datasource:
    url: jdbc:postgresql://localhost:5432/mydb
    username: myuser
    password: mypassword

logging:
  level:
    liquibase: DEBUG